import pandas as pd
import yaml
from snakemake.utils import min_version
from snakemake.utils import validate

min_version("5.1")

# ---- configuration

validate(config, "conf_schemas/snake_config.schema.yaml")

rnaseq_samples = pd.read_csv(
    config["rnaseq_samples"], sep = "\t"
).set_index(
    ["study_id", "sample_id", "run_id", "lane_id"], drop=False
)
validate(rnaseq_samples, "conf_schemas/rnaseq_samples.schema.yaml")

rnaseq_program_params = yaml.safe_load(
    open(config["rnaseq_program_params"], "r")
)
validate(rnaseq_program_params, "conf_schemas/rnaseq_program_params.schema.yaml")

# ---- rules

rule all:
    input:
        "doc/fake_report.pdf"

rule faker:
    output:
        "doc/fake_report.pdf"
    shell:
        """
        touch doc/fake_report.pdf
        """
